[colors]
background = '#fff8f8'
foreground = '#211a1d'

cursor_bg = '#874b6c'
cursor_fg = '#fff8f8'
cursor_border = '#874b6c'

selection_bg = '#ffd8e9'
selection_fg = '#211a1d'

ansi = ['#181115', '#8c270b', '#09721e', '#727f11', '#ff4eb4', '#72224e', '#874b6c', '#1a1a1a']
brights = ['#2e2e2e', '#a53d20', '#138c2b', '#8a9921', '#a2527e', '#ff3fcd', '#ff5966', '#1a1a1a']
